version: '2.2'
services:
  test-routes:
    image: alpine:latest
    environment:
      URLS: |
        http://asp-nginx/ 403
        http://asp-nginx/.htaccess 401
        http://asp-nginx/ASP/ 200
        http://asp-nginx/ASP/frontend/template.php 401
        http://asp-nginx/ASP/frontend/css/reset.css 200
        http://asp-nginx/ASP/frontend/js/jquery-ui.js 200
        http://asp-nginx/ASP/frontend/images/bf2logo.png 200
        http://asp-nginx/ASP/frontend/css/fonts/ptsans/PTS55F-webfont.woff 200
        http://asp-nginx/ASP/system 401
        http://asp-nginx/ASP/bf2statistics.php 200
        http://asp-nginx/ASP/getawardsinfo.aspx 200
        http://asp-nginx/ASP/getbackendinfo.aspx 200
        http://asp-nginx/ASP/getclaninfo.aspx 200
        http://asp-nginx/ASP/getleaderboard.aspx 200
        http://asp-nginx/ASP/getmapinfo.aspx 200
        http://asp-nginx/ASP/getplayerid.aspx 200
        http://asp-nginx/ASP/getplayerinfo.aspx 200
        http://asp-nginx/ASP/getrankinfo.aspx 200
        http://asp-nginx/ASP/getunlocksinfo.aspx 200
        http://asp-nginx/ASP/index.php 200
        http://asp-nginx/ASP/ranknotification.aspx 200
        http://asp-nginx/ASP/searchforplayers.aspx 200
        http://asp-nginx/ASP/selectunlock.aspx 200
        http://bf2sclone-nginx/ 200
        http://bf2sclone-nginx/.htaccess 401
        http://bf2sclone-nginx/cache 401
        http://bf2sclone-nginx/css/default.css 200
        http://bf2sclone-nginx/game-images/armies/0.png 200
        http://bf2sclone-nginx/js/nt2.js 200
        http://bf2sclone-nginx/queries/armies.list 401
        http://bf2sclone-nginx/queries/getArmiesByPID.php 401
        http://bf2sclone-nginx/site-images/online.png 200
        http://bf2sclone-nginx/template/config.inc.php.template 401
        http://bf2sclone-nginx/awards.inc.php 401
        http://bf2sclone-nginx/install.php.disabled 401
    networks:
      - bf2-network
    entrypoint:
      - /bin/sh
    command:
      - -c
      - |
          set -eu

          echo "Waiting for stack to be ready"
          s=0
          while true; do
              nc -vz -w 1 asp-nginx 80 \
                  && nc -vz -w 1 asp-php 9000 \
                  && nc -vz -w 1 bf2sclone-nginx 80 \
                  && nc -vz -w 1 bf2sclone-php 9000 \
                  && nc -vz -w 1 db 3306 \
                  && break || true
              s=$$(( $$s + 1 ))
              if [ "$$s" -eq 600 ]; then
                  exit 1
              fi
              echo "Retrying in 3 seconds"
              sleep 3
          done

          echo "$$URLS" | awk NF | while read -r i j; do
              if wget -q -SO- "$$i" 2>&1 | grep "HTTP/1.1 $$j " > /dev/null; then
                  echo "PASS: $$i"
              else
                  echo "FAIL: $$i"
                  exit 1
              fi
          done

networks:
  bf2-network:
